### ISSUE TITLE
"end kernel panic - not syncing: Fatal Exception in interrupt" on Debian and e1000

### ISSUE THREAD

**Issue by aminlatifi** [luigirizzo/netmap#422]
Hi,
I am using netmap bridge app on a Proxmox virtual machine. Debian 9 is installed on the machine  and two intel e1000 network cards has been attached.
I installed netmap patched driver (modprobe -r e1000; and next insmod LINUX/e1000/e1000.ko). Then run the bridge app with below command:
bridge  -i netmap:ens19 -i netmap:ens20  -v
Unfortunately the bridge app process show "Killed" message and immediately I got "end kernel panic - not syncing: Fatal Exception in interrupt" message from the kernel and system halt.
I also tried using bridge app without replacing e1000 module, but the app didn't work.

**Comment by vmaffione** [comment]
A stack trace would be needed here.please make sure to use the latest master

**Comment by giuseppelettieri** [comment]
If you where already using a recent master, please pull again. There as a bug affecting e1000 that is fixed in the current master.

**Comment by aminlatifi** [comment]
I pulled the source and tested again and problem still exists. I take an screen shot from Proxmox virtual machine after the system halt.

![screenshot from 2017-12-31 18-23-43](https://user-images.githubusercontent.com/5684607/34462413-b8a00882-ee58-11e7-8203-9e96630fa965.png)

**Comment by vmaffione** [comment]
It seems proxmox uses KVM. Can you reproduce this using QEMU with KVM support?

**Comment by Roman5951** [comment]
![13](https://user-images.githubusercontent.com/26681395/34914633-00aaaa12-f91f-11e7-82ab-fba22ec48597.png)

Hi! Through a virtual machine I wanted to install myself Kali Linux 3 But I have a error. How can I fix it?
