### ISSUE TITLE
Transparent mode not working

### ISSUE THREAD

**Issue by jibi** [luigirizzo/netmap#84]
I've got a problem with this code:

```c
#include <stdio.h>
#include <stdlib.h>
#include <poll.h>

#define NETMAP_WITH_LIBS
#include <net/netmap_user.h>

void
receiver(int fd, struct netmap_if *nifp)
{
	struct pollfd fds;
	struct netmap_ring *ring;
	unsigned int ring_id;
	unsigned int i;

	while (1) {
		fds.fd     = fd;
		fds.events = POLLIN;

		poll(&fds, 1, -1);

		for (ring_id = 0; ring_id < nifp->ni_rx_rings + 1; ring_id++) {

			ring         = NETMAP_RXRING(nifp, ring_id);

			ring->flags |= NR_FORWARD;
			ring->flags |= NR_TIMESTAMP;

			while (!nm_ring_empty(ring)) {
				i = ring->cur;
				printf("got packet from %s (ring %d, slot %d)\n", (ring_id == nifp->ni_rx_rings ? "host" : "NIC"), ring_id, i);
				ring->slot[i].flags |= NS_FORWARD;
				ring->head = ring->cur = nm_ring_next(ring, ring->cur);
			}
		}
	}
}

int
main()
{
	struct nm_desc *d;

	if (!(d = nm_open("netmap:eth0*", NULL, 0, 0))) {
		perror("nm_open\n");
	}
	receiver(d->fd, d->nifp);
	return 0;
}
```

What I want to do is just let all the traffic to flow from the host to the NIC and viceversa.

Running Netmap (branch master) on a Linux box with an ixgbe card, I've managed to hang the entire machine.
Basically:
- program won't quit
- I cannot put down the interface
- I cannot remove the ixgbe driver

(and of course the traffic is not flowing)

Is this a problem with Netmap or with my code?

**Comment by giuseppelettieri** [comment]
The latest commit should fix the deadlock (silly mistake, my fault). Please note, however, that transparent mode has been neglected for some time and is currently broken. We are looking into it.

**Comment by jibi** [comment]
I can confirm you that after syncinc with master I've got no locking problems anymore but the forwarding still does not work.

**Comment by giuseppelettieri** [comment]
Thanks for the testing. As I said, transparent mode is badly broken right now and the patch was not meant to fix that. We will try to put it back into shape in the next few days.

**Comment by giuseppelettieri** [comment]
The latest master tries to fix transparent mode. A bit of testing would be really appreciated.

**Comment by jibi** [comment]
Sure. As soon as possible I will give you some feedback with the e1000 and the ixgbe cards under Linux

**Comment by jibi** [comment]
After a quick test I can confirm you that the e1000 driver can work in transparent mode with the code I pasted.
However the ixgbe one is not working: I'm receiving packets on the 24th ring (which is the host ring as far as I understand) but they are not forwarded to the host stack.

**Comment by rincebrain** [comment]
I've tried with the latest patches using a VirtualBox VM and e1000 unpatched inside there (Debian 8.2), and I see sporadic traffic reports from e.g. the code above, but traffic fails to successfully forward while that application is running.

I could provide a copy of said VM or instructions for building an identical one, if that would be helpful.

**Comment by giuseppelettieri** [comment]
jibi, you probably already did this, since it is needed for e1000 also, but just to be sure: did you turn all hw accelerations off?

ethtool -K ethX  tx off rx off

**Comment by jibi** [comment]
no, I didn't do for the e1000 (I wasn't even aware).
I'll test with the ixgbe and I'll let you know.

**Comment by jibi** [comment]
no luck with hw accelerations turned off, still broken

**Comment by giuseppelettieri** [comment]
Hi jibi, I finally found the time to setup a pair of machines with ixgbe cards. Transparent mode works for me, with both the generic and native ixgbe netmap driver. Are you using the latest master? If yes, please give us more details to reproduce the failure, like, e.g., the VM setup you mentioned.

**Comment by jibi** [comment]
Ok, I can confirm that transparent mode is working with ixgbe (without the need to disable hw acceleration).
My fault.
Maybe I was not using master (or I had some wrong configuration that prevented the test program to work).

**Comment by giuseppelettieri** [comment]
OK, thank you for the testing. I am closing the issue now.
