### ISSUE TITLE
at nm_dispatch() ring->cur overruns ring->tail

### ISSUE THREAD

**Issue by M-Bernhard** [luigirizzo/netmap#883]
Hello,

I use netmap in conjunction with Suricata (IPS) under Linux.
Sporadically, the Ethernet interface used fails.
While troubleshooting, I found that in the function nm_dispatch ring->cur overruns ring->tail.
(All old buffers are sent again).

- GDB

Thread 2 "W#01-eth0" hit Breakpoint 1, nm_dispatch (cnt=-1, cb=0x5555556fbc30 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1091
1091    in /usr/include/net/netmap_user.h
$1010 = {self = 0x7ffff0274c30, fd = 5, mem = 0x7fffdb8df000, memsize = 343019520, done_mmap = 1, nifp = 0x7fffdb8df000, first_tx_ring = 0, last_tx_ring = 0, cur_tx_ring = 0, first_rx_ring = 0, last_rx_ring = 0, cur_rx_ring = 0, req = {nr_name = "eth0", '\000' <repeats 11 times>, nr_version = 14, nr_offset = 0, nr_memsize = 343019520, nr_tx_slots = 256, nr_rx_slots = 256, nr_tx_rings = 1, nr_rx_rings = 1, nr_ringid = 0, nr_cmd = 0, nr_arg1 = 0, nr_arg2 = 1, nr_arg3 = 0, nr_flags = 8193, spare2 = {0}}, hdr = {ts = {tv_sec = 1666007135, tv_usec = 704346}, caplen = 98, len = 98, flags = 0, d = 0x7ffff0274c30, slot = 0x7fffdb8f90d0, buf = 0x7fffdc07f800 ""}, some_ring = 0x7fffdb8f8000, buf_start = 0x7fffdc000000, buf_end = 0x7ffff0000000, snaplen = 0, promisc = 0, to_ms = 0, errbuf = 0x0, if_flags = 0, if_reqcap = 0, if_curcap = 0, st = {ps_recv = 0, ps_drop = 0, ps_ifdrop = 0}, msg = '\000' <repeats 511 times>}
(gdb)
Continuing.

Thread 2 "W#01-eth0" hit Breakpoint 2, nm_dispatch (cnt=-1, cb=0x5555556fbc30 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1119
1119    in /usr/include/net/netmap_user.h
$1011 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, head = 254, cur = 254, tail = 0, flags = 0, ts = {tv_sec = 1666007136, tv_usec = 704320}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
(gdb)
Continuing.

Thread 2 "W#01-eth0" hit Breakpoint 2, nm_dispatch (cnt=-1, cb=0x5555556fbc30 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1119
1119    in /usr/include/net/netmap_user.h
$1012 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, **head = 255, cur = 255, tail = 0**, flags = 0, ts = {tv_sec = 1666007136, tv_usec = 704320}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
(gdb)
Continuing.

Thread 2 "W#01-eth0" hit Breakpoint 2, nm_dispatch (cnt=-1, cb=0x5555556fbc30 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1119
1119    in /usr/include/net/netmap_user.h
$1013 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, **head = 1, cur = 1, tail = 0**, flags = 0, ts = {tv_sec = 1666007136, tv_usec = 704320}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
(gdb)
Continuing.

- Possible Fix

`diff --git a/sys/net/netmap_user.h b/sys/net/netmap_user.h`
`index e8983565..b0be8269 100644`
`--- a/sys/net/netmap_user.h`
`+++ b/sys/net/netmap_user.h`
`@@ -1126,8 +1126,10 @@ nm_dispatch(struct nm_desc *d, int cnt, nm_cb_t cb, u_char *arg)`
` 			d->hdr.len = d->hdr.caplen = slot->len;`
` 			while (slot->flags & NS_MOREFRAG) {`
` 				u_char *nbuf;`
`-				u_int oldlen = slot->len;`
`-				i = nm_ring_next(ring, i);`
`+				u_int oldlen = slot->len, x;`
`+				if ((x = nm_ring_next(ring, i)) == ring->tail)`
`+					break;`
`+				i = x;`
` 				slot = &ring->slot[i];`
` 				d->hdr.len += slot->len;`
` 				nbuf = (u_char *)NETMAP_BUF(ring, slot->buf_idx);`

**Comment by giuseppelettieri** [comment]
Hi @M-Bernhard, thanks for investigating this! However, I think that the bug is not in `nm_dispatch()` since, in our intentions, netmap should never pass a partial frame to userspace. This may be a bug in the rxsync routine of the driver. Which driver are you using?

**Comment by M-Bernhard** [comment]
Hello,

the behavior occurred in connection with the Intel drives e1000e and igb of the Linux kernel 5.10.128.

For the used IPS (Suricata) to work, various offloads have to be disabled. Possibly the problem is caused by this.

From Suricata User Guide, Relase 6.0.5 S.346

`for i in rx tx tso ufo gso gro lro tx nocache copy sg txvlan rxvlan; do`
`	/sbin/ethtool -K eth3 $i off 2>&1 > /dev/null;`
`done`

**Comment by giuseppelettieri** [comment]
mmm, OK. Those old drivers had been left a bit behind. I have pushed an update in the new `fix-older-drivers` branch. May you give it a try?

**Comment by M-Bernhard** [comment]
It now runs with the e1000e driver without problems. I will test the igb when I get the chance. But I assume that this will also work.

Many thanks

**Comment by M-Bernhard** [comment]
It seems that the error is not fixed after all. Today I had another failure.
With tcpdump I could see that all packets in the ring buffer were sent permanently again.
But since I don't know what kind of packets trigger the interface failure and it seems to occur only rarely now, it may take a while until I can provide more precise information.

**Comment by M-Bernhard** [comment]
Thread 2 "W#01-eth0" hit Breakpoint 1, nm_dispatch (cnt=-1, cb=0x5555556fccb0 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1118
1118    in /usr/include/net/netmap_user.h
$706 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, head = 255, cur = 255, tail = 0, flags = 0, ts = {tv_sec = 1666776975, tv_usec = 78412}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
[Switching to Thread 0x7ffff60d9640 (LWP 1227)]

Thread 2 "W#01-eth0" hit Breakpoint 2, nm_dispatch (cnt=-1, cb=0x5555556fccb0 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1131
**1131    in /usr/include/net/netmap_user.h**
$709 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, **head = 255, cur = 255, tail = 0**, flags = 0, ts = {tv_sec = 1666776975, tv_usec = 78412}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
[Switching to Thread 0x7ffff60d9640 (LWP 1227)]

Thread 2 "W#01-eth0" hit Breakpoint 1, nm_dispatch (cnt=-1, cb=0x5555556fccb0 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1118
1118    in /usr/include/net/netmap_user.h
$711 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, **head = 1, cur = 1, tail = 0**, flags = 0, ts = {tv_sec = 1666776975, tv_usec = 78412}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}
[Switching to Thread 0x7ffff60d9640 (LWP 1227)]

In another GDB session I wanted to see what kind of package was causing the problem - but there is no data in the buffer.

Thread 2 "W#01-eth0" hit Breakpoint 2, nm_dispatch (cnt=-1, cb=0x5555556fccb0 <NetmapCallback>, arg=0x7ffff0274b70 "\340K'\360\377\177", d=0x7ffff0274c30) at /usr/include/net/netmap_user.h:1131
1131    in /usr/include/net/netmap_user.h
$761 = {buf_ofs = 7372800, num_slots = 256, nr_buf_size = 2048, ringid = 0, dir = 0, head = 255, cur = 255, tail = 0, flags = 0, ts = {tv_sec = 1666778229, tv_usec = 230674}, offset_mask = 0, buf_align = 0, sem = '\000' <repeats 127 times>, slot = 0x7fffdb8f8100}

(gdb) print oldbuf
$762 = (u_char *) 0x7fffdc080800 ""
(gdb) x/10xb 0x7fffdc080800
0x7fffdc080800: 0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00
0x7fffdc080808: 0x00    0x00
(gdb) print **slot->len**
$764 = **0**

**Comment by giuseppelettieri** [comment]
ouch, I can see a silly bug. I don't know if this completely fixes the problem, but you should certainly apply the following
```
diff --git a/LINUX/if_e1000e_netmap.h b/LINUX/if_e1000e_netmap.h
index a9a80301f..595ce5c59 100644
--- a/LINUX/if_e1000e_netmap.h
+++ b/LINUX/if_e1000e_netmap.h
@@ -342,7 +342,7 @@ e1000_netmap_rxsync(struct netmap_kring *kring, int flags)
                if (n) { /* update the state variables */
                        rxr->next_to_clean = nic_i;
                        if (new_hwtail != (u_int)-1)
-                               kring->nr_hwtail = nm_i;
+                               kring->nr_hwtail = new_hwtail;
                }
                kring->nr_kflags &= ~NKR_PENDINTR;
        }
diff --git a/LINUX/if_igb_netmap.h b/LINUX/if_igb_netmap.h
index 7d7099e56..2a576f5c0 100644
--- a/LINUX/if_igb_netmap.h
+++ b/LINUX/if_igb_netmap.h
@@ -359,7 +359,7 @@ igb_netmap_rxsync(struct netmap_kring *kring, int flags)
                        rxr->next_to_alloc = nic_i;
 #endif /* NETMAP_LINUX_HAVE_IGB_NTA */
                        if (new_hwtail != (u_int)-1)
-                               kring->nr_hwtail = nm_i;
+                               kring->nr_hwtail = new_hwtail;
                }
                kring->nr_kflags &= ~NKR_PENDINTR;
        }
```

**Comment by M-Bernhard** [comment]
Unfortunately, that was not yet the solution.
But I can narrow down the error even better now.

At every first buffer pass (cur: 255 -> cur: 0) after opening (nm_open)
nm_dispatch jumps into the inner loop (and only at this time).
If at this time tail are 0 there is the overflow.
If tail is greater than 0 it is not noticed.

nm_dispatch:1126 cur: 253  tail: 254
nm_dispatch:1126 cur: 254  tail: 0
nm_dispatch:1126 cur: 255  tail: 0
**nm_dispatch:1131** i: 0  cur: 255  tail: 0
nm_dispatch:1126 cur: 1  tail: 0
nm_dispatch:1126 cur: 2  tail: 0
nm_dispatch:1126 cur: 3  tail: 0

nm_dispatch:1126 cur: 253  tail: 254
nm_dispatch:1126 cur: 254  tail: 2
nm_dispatch:1126 cur: 255  tail: 2
**nm_dispatch:1131** i: 0  cur: 255  tail: 2
nm_dispatch:1126 cur: 1  tail: 2
nm_dispatch:1126 cur: 2  tail: 3
nm_dispatch:1126 cur: 3  tail: 4
